services:
  app:
    image: ghcr.io/pleuvens/another-tracking-tool:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PHX_SERVER: "true"
      PORT: "4000"
      DATABASE_URL: "ecto://postgres:${DB_PASSWORD}@db/another_tracking_tool"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      PHX_HOST: "${PHX_HOST}"
      RESEND_API_KEY: "${RESEND_API_KEY}"
      MAILER_FROM_EMAIL: "${MAILER_FROM_EMAIL}"
      TMDB_ACCESS_TOKEN: "${TMDB_ACCESS_TOKEN}"
    command: sh -c "/app/bin/migrate && /app/bin/server"
    ports:
      - "4000:4000"

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: another_tracking_tool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
